name: Generate RF organisation Models

on:
  workflow_dispatch:

jobs:
  generate-models:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Install gnostic-grpc
        run: |
          go install github.com/google/gnostic@latest
          go install github.com/googleapis/gnostic-grpc@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Create output directory
        run: mkdir -p ./models/orgs

      - name: Create schema directory
        run: mkdir -p ./schema/

      - name: Download schema
        run: |
          curl -sSL "https://devportal-int.rf.se/portal/environments/DEFAULT/apis/9592815b-79a6-32d9-b98f-190299191414/pages/ed54bff8-4b5e-3c48-af3b-92c670b15b7e/content" -o ./schema/orgs.json

      - name: Run gnostic
        run: |
          gnostic --grpc-out=./models/orgs ./schema/orgs.json

      - name: Set up Git for commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit changes
        run: |
          git checkout -b gnostic-organisation-model-`date +'%Y-%m-%d'`
          git add models/organisation
          git commit -m "models: auto-generated gnostic organisation models"
          git push origin gnostic-organisation-model-`date +'%Y-%m-%d'`

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: auto-generated gnostic organisation models
          title: Update gnostic models
          body: This PR contains updated models generated by gnostic.
          branch: gnostic-organisation-model-`date +'%Y-%m-%d'`
          base: main
